version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: analytics_app
    depends_on:
      - db
    ports:
      - "8000:8000"  
      - "3000:3000"  
    volumes:
      - .:/app  
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db 
      - DB_PORT=${DB_PORT}

volumes:
  postgres_data: