# dbt_project/models/staging/sources.yml
version: 2

sources:
  - name: raw_telegram
    description: "Raw data loaded from the Telegram scraper."
    schema: raw
    tables:
      - name: telegram_messages
        description: "Contains one row per message with the raw JSON payload."
      - name: image_detections # <-- ADD THIS NEW TABLE DEFINITION
        description: "Raw object detection results from YOLO model."